### ISSUE TITLE
Fixed units tests

### ISSUE THREAD

**Issue by antogh** [Azure-Samples/service-fabric-dotnet-web-reference-app#10]
Yesterday I tried unit tests for this project, it was interesting to see how they were done (although I guess I'd not be able to create a MockReliableStateManager from scratch by myself, in case I'd need it I'd just copy this one) 
There were a couple of issues in the sources that were causing the tests to fail with exceptions, I fixed them, should I make a description of the fixes here or fork the repo and create a pull request?

**Comment by masnider** [comment]
We love pull requests!

**Comment by antogh** [comment]
Here you go Matt, i just created the pull request. I hope is clear enough, it was a bit late :) 
Cheers
Antonio

**Comment by masnider** [comment]
Hey there, sorry I never replied here. We took your PR in, so thanks for the help!
