### ISSUE TITLE
Unit tests are missing(?)

### ISSUE THREAD

**Issue by dtoomey** [Azure-Samples/service-fabric-dotnet-web-reference-app#18]
I cannot find the unit tests referred to on the documentation page. Have they been removed? Would really like to see an example of how to test these services.

**Comment by Dismissile** [comment]
It looks like commit [4a64def](https://github.com/Azure-Samples/service-fabric-dotnet-web-reference-app/commit/4a64defc66df8dce663ad3dc676f29735b4a391f#diff-db5e22a6f049b842793759ecbcbe18f1) removed the unit test projects from the solution. They are still in the folder, though. I'm not sure if this was done by accident or not.

**Comment by masnider** [comment]
This was intentional (on my part) due to the fact that in the run-up to GA there were many breaking changes that caused the test projects to not work or that broke certain tests. We are working on re-enabling the test projects.

**Comment by masnider** [comment]
These were re-added in the last set of changes.
