### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by RhysC** [Azure-Samples/service-fabric-dotnet-web-reference-app#19]
HTTP  is not really valid for any app being built in service fabric, yet all the examples seems to be insecure. If its non-trivial to do HTTPS then perhaps we fix that too?

**Comment by masnider** [comment]
When you say http isn't valid you just mean insecure traffic isn't valid?

**Comment by RhysC** [comment]
Yup. In what scenario is insecure transmission valid especially while using
something as complex as service fabric. This isn't a static marketing site
that is being demo'd.
All of the links in the example comments are even all HTTPS.
It's really starting to bother me that MS don't seem to properly
acknowledge HTTPS in dev cycles yet it's practically required for the real
world
On 26 Apr 2016 22:05, "Matt" notifications@github.com wrote:

When you say http isn't valid you just mean insecure traffic isn't valid?

**Comment by masnider** [comment]
Hm. Well to say that we aren't paying attention is an unfair characterization. Service Fabric provides scripts and documentation for setting up secure clusters on both your local box and in Azure. Here's a like to a different issue where someone asked how to configure it. It contains a good discussion with examples and pointers to docs where it is described how to configure both applications and the cluster as a whole. If you think these docs aren't clear or don't provide sufficient information, please let us know. https://github.com/Azure-Samples/service-fabric-dotnet-web-reference-app/issues/3. From your question it wasn't clear whether you were concerned about securing your cluster or securing communication between services, but fortunately that conversation covers both. As to your question about when it is valid I would of course say demos only - examples like this where we are trying to teach people how generally to work with Service Fabric and have to make the tradeoff between that additional complexity and explaining the Service Fabric related aspects of the project. That said this sample in particular does have a roadmap to be improved to show secure communication (as well as integration with other Azure services for doing so). If you have particular things you want to see secured feel free to call them out (we also accept PRs :) ) but I don't think saying that we don't care is a fair characterization at all.
