### ISSUE TITLE
ServiceEventSource usage is not thread-safe

### ISSUE THREAD

**Issue by ShaneCourtrille** [Azure-Samples/service-fabric-dotnet-web-reference-app#26]
The ServiceEventSource.Current gets called from OrdersController but it's defined as...

```
internal sealed class ServiceEventSource : EventSource {
        public static readonly ServiceEventSource Current = new ServiceEventSource();
}
```

That doesn't seem thread safe at all?  I know it's a just a sample but still

**Comment by karolz-ms** [comment]
Static member initialization is guaranteed to run only once per app domain, so it is not an issue.

**Comment by ShaneCourtrille** [comment]
That's the point though.  If you have two separate calls to OrdersController at the same time then occasionally they will both be writing to the same ServiceEventSource.Current.

**Comment by karolz-ms** [comment]
Yes. That is by design too. EventSource.WriteXxx() methods are thread safe. In fact, you _cannot_ have more than one instance of an EventSource (with a distinct Name) per app domain.
