### ISSUE TITLE
Password problem for PFK certificate

### ISSUE THREAD

**Issue by adamsives** [Azure-Samples/service-fabric-dotnet-web-reference-app#37]
I registered for Azure Service Fabric Party Cluster. After registration it provided two keys: PFX and PEM .The instructions given at https://try.servicefabric.azure.com/sfxhelp.html and says that while installing on Windows, if it asks for password, leave it empty and proceed.But while installing it is asking for password. When leaving empty it is showing error: "Password entered is incorrect".How to install it without password?

**Comment by unmeshk11** [comment]
The PFX file was in incorrect format and the PEM was missing the private key. The issues are fixed now. I also removed the PEM link because you can easily convert the PFX to PEM using openssl. The sfxhelp.html now gives exact scripts to run to use the cert and connect using PS, CLI or SFX.
