### ISSUE TITLE
"Running this Sample" Is Missing Something

### ISSUE THREAD

**Issue by antoinne85** [Azure-Samples/service-fabric-dotnet-web-reference-app#5]
I followed the directions for running the sample (namely, load the solution and hit F5), however, because the App.config for the Inventory.Service project throws exceptions because the appSettings have a value of TBA.

I'm just getting started with ServiceFabric. I'm not entirely sure what goes here (though I might be able to make some guesses) but it's probably worth putting into the directions to better inform the user.

After spending some more time with it, I think the change to make is to default to local backups, instead of Azure, and adjust the code so that it only attempts to read and use the appSettings if Azure backups are specified. 

If I get some time soon I might attempt that if its a welcome change.

**Comment by mani-ramaswamy** [comment]
Thanks for trying it out. I will place the variable declarations for backing up to Azure in a conditional block  so that this problem will be fixed, as well as add additional documentation. Providing actual credentials will work, of course. Meanwhile, you can comment out all the lines that rely on the appSettings and only enable the backup to be stored locally.

**Comment by tylerd** [comment]
There are 3 TBA items in the app.config for Inventory Service. Including a Blob Service Endpoint address. Are there missing steps when setting up this sample?

**Comment by mani-ramaswamy** [comment]
These are Azure credentials to be provided by the customer.  I have an update to the reader that explains this which I will push out in a day or two.

On Jan 4, 2016, at 11:56 AM, Tyler D <notifications@github.com<mailto:notifications@github.com>> wrote:

There are 3 TBA items in the app.config for Inventory Service. Including a Blob Service Endpoint address. Are there missing steps when setting up this sample?

##

**Comment by antoinne85** [comment]
I'm not sure I would say that steps are explicitly missing, but a brief reading of the code seems to imply that I have two choice for sampling the backup/restore functionality (a local filesystem option and a blob storage option). But upon running the code you find that, in fact, you must supply blob storage credentials to run the sample. 

It would be nice if the user really got to switch from local to blob in its entirety.

**Comment by mani-ramaswamy** [comment]
There are two choices – local and blob. If the blob is selected then, the credentials are to be provided. If local is set, then, you shouldn’t have to supply the blob credentials. I had checked in a change a few days ago that allows you to backup to local directories alone.

**Comment by masnider** [comment]
In the latest updates we've also improved this. I'm going to close this issue for now, but I will also start work on improving the documentation inside the sample to indicate what fields are necessary. Part of this has been improved already by moving the necessary settings for each type of backup into their own specific service configuration sections. After we get that all committed please take another look and open another issue (or reopen this one) if you still think things are unclear.
