### ISSUE TITLE
Unable to Run - FileNotFoundException

### ISSUE THREAD

**Issue by antoinne85** [Azure-Samples/service-fabric-dotnet-web-reference-app#6]
After commenting out the Azure-related code in the BackupStore (as suggested for Issue #5), I get FileNotFoundExceptions when attempting to run the sample.

I've attached a screenshot that attempts to gather as much information as possible for you, as well as the contents of the Output window.

The cluster is installed in the default location (C:\SfDevCluster). 

[OutputWindow.txt](https://github.com/Azure-Samples/service-fabric-dotnet-web-reference-app/files/60544/OutputWindow.txt)
![filenotfoundexception](https://cloud.githubusercontent.com/assets/182187/11768345/4e069f9a-a198-11e5-810b-b3e7474a999a.png)

If there's anything else I can provide, please let me know.

Edit: 
I should add--I'm running VS 2015 Community Edition. VS is running as Administrator. I've also executed the PowerShell execution-policy script found at: https://azure.microsoft.com/en-us/documentation/articles/service-fabric-get-started/

**Comment by antoinne85** [comment]
Is there a symbol source out there that has the symbols for these assemblies? That might assist me (and others) in tracking down these issues when we encounter them.

As it stands, its not easy to even determine what file is missing.

**Comment by antoinne85** [comment]
I may have found the problem, though I won't be able to verify it until tomorrow.

I set up the environment on another PC and ran the code. It worked.

As I was re-commenting out the Azure-y bits, I noticed line 48 in InventoryService.cs. Coincidentally, the machine I was running on *had* an E drive. The machine that was failing *does not*.

It might be worthwhile to do one of the following:
* Move the storage location to C.
* Use Environment.GetLogicalDrives to pick some drive that does exist.
* Move this particular bit of configuring to the .config file (and perhaps the Azure/Local decision as well, so that the consumer might just have two blocks of XML, and they can comment/uncomment the one they want to use.

I'll test this out in the morning and update.

**Comment by antoinne85** [comment]
I managed to get the sample working on another machine, so it's probably not a problem with the code (unless there's some hardcoded path somewhere, but it seems to blow up before any of the BackupStore stuff comes into play, so that seems unlikely).

In light of this, closing the issue.

**Comment by masnider** [comment]
Sorry for the lack of response till now. Glad you got it sorted. I'll make sure the sample owner takes a look anyway to see if we can make things more robust.
