### ISSUE TITLE
Number of services instances created after startup 

### ISSUE THREAD

**Issue by antogh** [Azure-Samples/service-fabric-dotnet-web-reference-app#9]
Hello, I have a doubt about the number of instances created when I launch the application.
Without doing any action in the browser (like adding an item to inventory or placing and order) I have already 5 instances of InventoryService (I mean 5 primary partitions with their 2 replicas) 
Right now I can't figure who created these instances and why they are 5. Normally I'd think one new instance of InventoryService would be created when I add a new item in the admin.html (if an instance of InventoryService with the partition key of the item is not yet existing), these new instance would have 1 item in its collection state. So I don't understand where this 5 instances with 0 items in the collection state were created. Is the fabricRuntime.RegisterServiceType function that creates these instances? And then why I have 5 InventoryService, 9 CustomerOrderActorService, 3 RestockRequestActorService, 1 RestockRequestManager and 1 WebService? 
Thank you for your answer.

**Comment by masnider** [comment]
The sample currently uses default services, which get auto-created as soon as the application instance is created. You can see the current configuration here: https://github.com/Azure-Samples/service-fabric-dotnet-web-reference-app/blob/master/ReferenceApp/WebReferenceApplication/ApplicationManifest.xml

**Comment by antogh** [comment]
Thank you Matt, now it all make sense again ;) 
I studied the SF partitioning before the holidays and now practicing with this sample apparently I was a bit confused, I hope with this refresh the info will persist in my mind.
Quoting Dr. Minsky "You don't understand anything until you learn it more than one way"
Cheers

**Comment by fp0n** [comment]
Matt,
This one tripped me up to for a bit.  Could the default ApplicationManifest.xml be changed to use the parameters at the top of the file and all the parameters be defined?

``    <Service Name="RestockRequestActorService" GeneratedIdRef="cd8c75cc-03eb-4aec-ab00-dd3cc5048d9d|None">
      <StatefulService ServiceTypeName="RestockRequestActorServiceType" TargetReplicaSetSize**="[RestockRequestActorService_TargetReplicaSetSize]"** MinReplicaSetSize**="[RestockRequestActorService_MinReplicaSetSize]">**
        <UniformInt64Partition PartitionCount**="[RestockRequestActorService_PartitionCount]"** LowKey="-9223372036854775808" HighKey="9223372036854775807" />
      </StatefulService>
    </Service>

**Comment by masnider** [comment]
Sure you could, but keep in mind that default services are not the recommended mechanism for creating services in production since changing them requires upgrading the whole named application instance.

**Comment by fp0n** [comment]
Matt,

The way the project is setup now, the Local.1Node.xml and Local.5Node.xml configurations don't work.  Local 1 Node in particular is useful for debugging services as you usually only want 1 copy of the service and 1 Node.  
[Service-Fabric-Web-Ref-issue_9.zip](https://github.com/Azure-Samples/service-fabric-dotnet-web-reference-app/files/804125/Service-Fabric-Web-Ref-issue_9.zip)

I understand your concern about production - I thought that is what the various config files (Cloud.xml, Local.1Node.xml and Local.5Node.xml) were meant to model.  Sorry the delay in getting back - I was traveling.

Thanks.
